server:
  port: 9901

spring:
  redis:
    host: 192.168.83.100
    port: 6379
    database: 0
    timeout: 500
    password: "wangqiubao"
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
        max-wait: 500